### ISSUE TITLE
Upgrade base64

### ISSUE THREAD

**Issue by tirkarthi** [tailhook/ssh-keys#2]
Hi,

It seems ssh-keys uses a version of the base64 library which is vulnerable to security issues. Please refer to https://github.com/RustSec/advisory-db/blob/master/Advisories.toml#L53 .

patch commit : https://github.com/alicemaz/rust-base64/commit/24ead980daf11ba563e4fb2516187a56a71ad319
patched version : [">= 0.5.2"]
used version : base64 = ^"0.2.1"

This is done using crates.io data. Feel free to close this issue if it's not relevant.

Thanks

**Comment by tailhook** [comment]
Updated and released a new version. Thank you for report!

**Comment by tirkarthi** [comment]
You're welcome. Please consider adding [cargo-audit](https://github.com/RustSec/cargo-audit) to the CI to get notified in the future.

Thanks
